//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThuVienSach_NguyenNgocVy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHI_TIET_GIAO_DICH
    {
        public int MaCTGD { get; set; }
        public Nullable<int> MaGD { get; set; }
        public Nullable<int> MaSach { get; set; }
        public int SoLuong { get; set; }
        public decimal GiaTien { get; set; }
        public string TrangThai { get; set; }
    
        public virtual SACH SACH { get; set; }
        public virtual GIAO_DICH GIAO_DICH { get; set; }
    }
}
